//! Regression tests against MATLAB f64 golden reference data.
//!
//! Test data is embedded as static Rust arrays in `rls_regression/golden_cases.rs`,
//! generated from MATLAB by `comparison/generate_rls_golden_rs.py`.

#![allow(clippy::needless_range_loop)]

#[path = "rls_regression/golden_cases.rs"]
mod golden_cases;

use flight_solver::rls::{CovarianceGuards, RlsParallel};
use nalgebra::SVector;

/// f32 vs f64 tolerance. MATLAB uses f64; our solvers use f32.
const TOL: f32 = 5e-2;

fn run_cases<const N: usize, const P: usize>(cases: &[golden_cases_mod::Case<N, P>]) {
    let guards = CovarianceGuards {
        cov_max: f32::MAX,
        cov_min: f32::MAX,
        max_order_decrement: 0.1,
    };

    for case in cases {
        let mut rls = RlsParallel::<N, P>::new(case.gamma, case.lambda, guards);

        for &(ref a_arr, ref y_arr) in case.steps {
            let a = SVector::<f32, N>::from_column_slice(a_arr);
            let y = SVector::<f32, P>::from_column_slice(y_arr);
            rls.update(&a, &y);
        }

        for n_idx in 0..N {
            for p_idx in 0..P {
                let actual = rls.params()[(n_idx, p_idx)];
                let expected = case.final_x[n_idx][p_idx];
                let diff = (actual - expected).abs();
                let scale = expected.abs().max(1.0);
                assert!(
                    diff / scale < TOL,
                    "[{}] X[{},{}]: actual={:.6}, expected={:.6}, rel={:.2e}",
                    case.name,
                    n_idx,
                    p_idx,
                    actual,
                    expected,
                    diff / scale,
                );
            }
        }
    }
}

/// Generic Case type matching the layout generated by golden_cases.rs.
mod golden_cases_mod {
    pub struct Case<const N: usize, const P: usize> {
        pub name: &'static str,
        pub gamma: f32,
        pub lambda: f32,
        pub steps: &'static [([f32; N], [f32; P])],
        pub final_x: [[f32; P]; N],
    }
}

macro_rules! regression_test {
    ($test_name:ident, $mod:ident, $n:literal, $p:literal) => {
        #[test]
        fn $test_name() {
            let cases = &golden_cases::$mod::CASES;
            // golden_cases::$mod::Case and golden_cases_mod::Case<N, P> have
            // identical layout (same fields, same types, same order).
            let cases: &[golden_cases_mod::Case<$n, $p>] = unsafe {
                core::slice::from_raw_parts(
                    cases.as_ptr() as *const golden_cases_mod::Case<$n, $p>,
                    cases.len(),
                )
            };
            run_cases(cases);
        }
    };
}

regression_test!(regression_n2_p1, n2_p1, 2, 1);
regression_test!(regression_n4_p1, n4_p1, 4, 1);
regression_test!(regression_n4_p3, n4_p3, 4, 3);
regression_test!(regression_n4_p6, n4_p6, 4, 6);
regression_test!(regression_n8_p3, n8_p3, 8, 3);
regression_test!(regression_n8_p6, n8_p6, 8, 6);
